version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: boat_tent
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 074546
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "host=db port=5432 user=postgres dbname=boat_tent sslmode=disable password=123456"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: "http://localhost:8080"

volumes:
  pgdata:
